//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himawari.Alias.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Himawari.Alias.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End game..
        /// </summary>
        internal static string EndGame {
            get {
                return ResourceManager.GetString("EndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t cheat!.
        /// </summary>
        internal static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game as ended. Thank you for participation..
        /// </summary>
        internal static string GameEnded {
            get {
                return ResourceManager.GetString("GameEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is not started..
        /// </summary>
        internal static string GameIsNotStarted {
            get {
                return ResourceManager.GetString("GameIsNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change word..
        /// </summary>
        internal static string NextWord {
            get {
                return ResourceManager.GetString("NextWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but presenter has been already chosen..
        /// </summary>
        internal static string PresenterAlreadyChosen {
            get {
                return ResourceManager.GetString("PresenterAlreadyChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, the next presenter is {0}..
        /// </summary>
        internal static string PresenterChosen {
            get {
                return ResourceManager.GetString("PresenterChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See word..
        /// </summary>
        internal static string SeeWord {
            get {
                return ResourceManager.GetString("SeeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, let&apos;s start playing alias. Who wants to be the presenter?.
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want!.
        /// </summary>
        internal static string Want {
            get {
                return ResourceManager.GetString("Want", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hurray, you guessed the word! Who wants to be the next?.
        /// </summary>
        internal static string CorrectGuess {
            get {
                return ResourceManager.GetString("CorrectGuess", resourceCulture);
            }
        }
        
        internal static string PartialGuess {
            get {
                return ResourceManager.GetString("PartialGuess", resourceCulture);
            }
        }
    }
}
