//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Himawari.Application.Resources {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WhoCommandVariants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WhoCommandVariants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Himawari.Application.Resources.WhoCommandVariants", typeof(WhoCommandVariants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I belive that.
        /// </summary>
        internal static string Believe {
            get {
                return ResourceManager.GetString("Believe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spirits told me.
        /// </summary>
        internal static string Spirits {
            get {
                return ResourceManager.GetString("Spirits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars told me.
        /// </summary>
        internal static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I suppose.
        /// </summary>
        internal static string Suppose {
            get {
                return ResourceManager.GetString("Suppose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think.
        /// </summary>
        internal static string Think {
            get {
                return ResourceManager.GetString("Think", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind wispered me.
        /// </summary>
        internal static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witch made a jinx that.
        /// </summary>
        internal static string Witch {
            get {
                return ResourceManager.GetString("Witch", resourceCulture);
            }
        }
    }
}
