# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dev" ]

jobs:    
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
         
      - name: Remove old GitHub packages
        run: |
          dotnet nuget remove source Github 
      
      - name: Add new Github packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/Geneirodan/index.json" \
            --name Github \
            --username Geneirodan \
            --password ${{ secrets.PACKAGES_TOKEN }} \
            --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release
